--- #YAML:1.0
name: Template-Stash-EscapeHTML
version: 0.01
author:
  - Tomohiro IKEBE <ikebe@shebang.jp>
abstract: escape HTML automatically in Template-Toolkit.
license: perl
generated_by: Module::Build version 0.2611, without YAML.pm
